version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(filename)s:%(lineno)d | %(message)s"

# Simple to use console to show the logs and detailed logs are with timestamp are saved to a log file
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  rotating:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/stream_rotating.log
    maxBytes: 5000000
    backupCount: 3


loggers:
  appLogger:
    level: DEBUG
    handlers: [console, rotating]
    propagate: False